version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: ${DB_PORT}
    working_dir: /app/djangoTemplate
    depends_on:
      - db
    command: >
      sh -c "until nc -z -v -w30 db 5432; do echo 'Esperando a la base de datos...'; sleep 1; done &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

volumes:
  db_data: